apiVersion: v2
name: nlp-ingestion
description: The IDEA4RC NLP Ingestion Service processes and stores the data from the NLP pipeline.

type: application
version: 14.07.25-1000
appVersion: 14.07.25-1000