apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nlpingestion.resultsui.service.name }}
  namespace: {{ .Values.nlpingestion.namespace }}
spec:
  ports:
    - port: {{ .Values.nlpingestion.resultsui.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.nlpingestion.resultsui.name }}