## OMOP ETL values
name: omop-etl
namespace: datamesh
replicas: 1
#image: "idea2omop:latest"
image: "ghcr.io/idea4rc/etl-idea2omop:3.0-AMD"
imagePullPolicy: IfNotPresent
#port: 3000 # does it need to be exposed? is it the correct port?
#service:
#  name: omop-etl-svc
#  port: 3000
#  targetPort: 3000
#  type: ClusterIP
datasource:
  metadata:
    dbPort: 5432
    dbName: metadata
    driverClassName: org.postgresql.Driver
    image: postgres:16.3-bullseye
    replicas: 1
    service:
      name: omop-etl-postgres-db
      port: 5432
      targetPort: 5432
      type: ClusterIP
  source:
    dbSvc: etl-postgres-db.datamesh.svc.cluster.local
    dbPort: 5432
    dbName: etl
    driverClassName: org.postgresql.Driver
  omop:
    dbSvc: omop-postgres-service.datamesh.svc.cluster.local
    dbPort: 5432
    dbName: omopdb
    driverClassName: org.postgresql.Driver
    schemaCDM: results

# Additional configuration that's related to the capsule environment
idea4rcStorageClass:
  name: idea4rc-hostpath
