{{- $PasswordValue := (randAlpha 16) | b64enc }}
{{- $secret := (lookup "v1" "Secret" .Values.namespace "omop-etl-db-secret") }}
{{- if $secret }}
  {{- $PasswordValue = index $secret.data "OMOP_ETL_PGSQL_PASSWORD" }}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: omop-etl-db-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  OMOP_ETL_PGSQL_USER: {{ "postgres" | b64enc }}
  OMOP_ETL_PGSQL_PASSWORD: {{ $PasswordValue}}