#Capsule Workbench Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}
          env:
            - name: KAFKA_CONSUMER_ID
              value: {{ .Values.kafka.consumerId }}
            - name: KAFKA_FHIR_TOPIC
              value: {{ .Values.kafka.fhirTopic }}
            - name: KAFKA_FHIR_RESULT_TOPIC
              value: {{ .Values.kafka.queryResultTopic }}
            - name: KAFKA_SQL_TOPIC
              value: {{ .Values.kafka.sqlTopic }}
            - name: KAFKA_SQL_RESULT_TOPIC
              value: {{ .Values.kafka.sqlResultTopic }}
            - name: KAFKA_HOST
              value: {{ .Values.kafka.host }}
            - name: KAFKA_PORT
              value: "{{ .Values.kafka.port }}"
            - name: KAFKA_CLIENT_ID
              value: {{ .Values.kafka.clientId }}
            - name: KAFKA_CA_PEM
              value: "./conf/certs/ca.pem"
            - name: KAFKA_CLIENT_KEY_PEM
              value: "./conf/certs/client.key.pem"
            - name: KAFKA_CLIENT_CERT_PEM
              value: "./conf/certs/client.cert.pem"
            - name: SERVICE_URL
              value: {{ .Values.serviceURL }}
            - name: FHIR_SERVER_URL
              value: {{ .Values.fhirServerURL }}
            - name: PRODUCTION
              value: "{{ .Values.production }}"
            - name: AUDIT_URL
              value: {{ .Values.auditURL }}
            - name: POSTGRESS_URL
              value: {{ .Values.postgres.URL }}
            - name: POSTGRESS_PORT
              value: "{{ .Values.postgres.port }}"
            - name: POSTGRESS_USER
              valueFrom:
                secretKeyRef:
                  name: etl-secret
                  key: ETL_PGSQL_USER
            - name: POSTGRESS_DB
              value: {{ .Values.postgres.dbName }}
            - name: POSTGRESS_PWD
              valueFrom:
                secretKeyRef:
                  name: etl-secret
                  key: ETL_PGSQL_PASSWORD
            - name: KEYCLOAK_URL
              value: {{ .Values.keyCloak.URL }}
            - name: KEYCLOAK_PORT
              value: "{{ .Values.keyCloak.port }}"
            - name: KEYCLOAK_HOST
              value: {{ .Values.keyCloak.host }}
            - name: CLIENT_ID
              value: {{ .Values.keyCloak.clientId }}
            - name: CLIENT_SECRET
              value: {{ .Values.keyCloak.clientSecret }}
          ports:
            - containerPort: {{ .Values.port }}
          volumeMounts:
            - name: query-executor-kafka-tls-auth-secrets
              mountPath: /app/dist/conf/certs/
      volumes:
        - name: query-executor-kafka-tls-auth-secrets
          secret:
            secretName: query-executor-kafka-tls-auth
