{{- $PasswordValue := (randAlpha 16) | b64enc }}
{{- $secret := (lookup "v1" "Secret" .Values.namespace "fcbe-keycloak-secret") }}
{{- if $secret }}
  {{- $PasswordValue = index $secret.data "CLIENT_SECRET" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: "fcbe-keycloak-secret"
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  CLIENT_ID: {{ "query-executor" | b64enc }}
  CLIENT_SECRET: {{ $PasswordValue }}